#!/usr/bin/env python3
"""Validate that pinned upstream skills are present verbatim.

The manifest is generated by the vendor workflow from the pinned source commit.
This gate deliberately validates Git blob hashes, not names or frontmatter claims.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / ".agents" / "UPSTREAM_SOURCES.json"
SKILL_ROOT = ROOT / ".agents" / "skills"


def git_blob_sha(data: bytes) -> str:
    header = f"blob {len(data)}\0".encode("ascii")
    return hashlib.sha1(header + data).hexdigest()


def fail(message: str) -> None:
    raise SystemExit(f"FAIL: {message}")


def main() -> None:
    if not MANIFEST.exists():
        fail(".agents/UPSTREAM_SOURCES.json is missing; upstream provenance is not verifiable")

    payload = json.loads(MANIFEST.read_text(encoding="utf-8"))
    skills = payload.get("skills") or []
    if not skills:
        fail("upstream manifest contains no skills")

    required = {
        "seo-keyword",
        "seo-content-audit",
        "seo-onpage",
        "seo-technical",
        "content-brief-authoring",
        "content-and-copy",
        "editorial-qa",
        "evidence-based-reviews",
        "information-architecture",
        "jtbd-framing",
        "cro-optimization",
        "seo-competitor",
        "seo-aeo-geo",
        "brand-voice",
    }
    present = {entry.get("skill") for entry in skills}
    missing_skills = sorted(required - present)
    if missing_skills:
        fail("manifest is missing required full upstream skills: " + ", ".join(missing_skills))

    errors: list[str] = []
    for entry in skills:
        skill = entry["skill"]
        if entry.get("vendoring") != "verbatim-directory":
            errors.append(f"{skill}: vendoring must be verbatim-directory")
            continue

        root = SKILL_ROOT / skill
        if not root.exists():
            errors.append(f"{skill}: local directory missing")
            continue

        expected = {item["path"]: item["blob_sha"] for item in entry.get("files", [])}
        actual_paths = {
            path.relative_to(root).as_posix()
            for path in root.rglob("*")
            if path.is_file()
        }
        if actual_paths != set(expected):
            missing = sorted(set(expected) - actual_paths)
            extra = sorted(actual_paths - set(expected))
            if missing:
                errors.append(f"{skill}: missing files {missing}")
            if extra:
                errors.append(f"{skill}: unexpected files {extra}")

        for rel, expected_sha in expected.items():
            path = root / rel
            if not path.exists():
                continue
            actual_sha = git_blob_sha(path.read_bytes())
            if actual_sha != expected_sha:
                errors.append(
                    f"{skill}/{rel}: modified vendored file "
                    f"(expected {expected_sha}, got {actual_sha})"
                )

    if errors:
        fail("\n".join(errors))

    print(
        f"PASS: {len(skills)} pinned upstream skill directories match their Git blob hashes "
        f"from {payload.get('source_commit')}"
    )


if __name__ == "__main__":
    main()
